# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[(b'MR', b'Mr.'), (b'MRS', b'Mrs.'), (b'MS', b'Ms.')], max_length=3)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(to='personel.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('place', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Grader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgrader', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('folders', models.IntegerField()),
                ('cbooks', models.IntegerField()),
                ('cfolders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('status', models.CharField(max_length=1)),
                ('folderF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Folder')),
                ('graderF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Grader')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('stype', models.IntegerField(choices=[(1, b'Gymnasio'), (2, b'Lykeio'), (3, b'Idiwtiko')])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afm', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('specialty', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='graders',
            field=models.ManyToManyField(through='personel.Grader', to='personel.Teacher'),
        ),
        migrations.AddField(
            model_name='grader',
            name='lessonF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Lesson'),
        ),
        migrations.AddField(
            model_name='grader',
            name='teacherF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Teacher'),
        ),
        migrations.AddField(
            model_name='folder',
            name='lessonF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Lesson'),
        ),
        migrations.AddField(
            model_name='folder',
            name='registers',
            field=models.ManyToManyField(through='personel.Registry', to='personel.Grader'),
        ),
    ]
