# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_auto_20180602_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='statusTime',
            field=models.DateTimeField(blank=True, default=b'2018-06-08 13:41:58'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actionTime',
            field=models.DateTimeField(default=b'2018-06-08 13:41:58'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='codeAfm',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='codeGrad',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
