# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0004_auto_20160713_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='grader',
            old_name='cgrader',
            new_name='coordinator',
        ),
        migrations.RenameField(
            model_name='grader',
            old_name='lessonF',
            new_name='fidLesson',
        ),
        migrations.RenameField(
            model_name='grader',
            old_name='teacherF',
            new_name='fidTeacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='afm',
            new_name='codeAfm',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='code',
            new_name='codeGrad',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='specialty',
            new_name='codeSpec',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cbooks',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='cfolders',
        ),
        migrations.AddField(
            model_name='grader',
            name='graderC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grader',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='booksC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='foldersC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='folders',
            field=models.IntegerField(default=0),
        ),
    ]
