# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0008_auto_20160730_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='date',
            new_name='actionTime',
        ),
    ]
