# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0009_auto_20160730_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(default=b'\xce\x98\xce\xb5\xcf\x84\xce\xb9\xce\xba\xce\xae\xcf\x82', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='type',
            field=models.CharField(default=b'\xce\x97\xce\xbc\xce\xb5\xcf\x81\xce\xae\xcf\x83\xce\xb9\xce\xbf', max_length=16),
        ),
    ]
