# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0010_auto_20160809_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchooltoGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(1, b'\xce\x97\xce\x9c\xce\x95\xce\xa1\xce\x97\xce\xa3\xce\x99\xce\x9f'), (2, b'\xce\x95\xce\xa3\xce\xa0\xce\x95\xce\xa1\xce\x99\xce\x9d\xce\x9f')], default=1)),
                ('codeDDE', models.CharField(max_length=3)),
                ('nameDDE', models.CharField(max_length=64)),
            ],
        ),
    ]
