# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0011_schooltograde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooltograde',
            name='type',
        ),
    ]
