# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0012_remove_schooltograde_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='isNow',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='regAction',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='regStatus',
        ),
        migrations.AddField(
            model_name='registry',
            name='location',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registry',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
