# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0013_auto_20160814_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='bookCount',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folderNo',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folderStatus',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='isNow',
        ),
        migrations.AddField(
            model_name='folder',
            name='books',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
