# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-14 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0014_auto_20160814_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='typeChar',
            field=models.CharField(default=b'A', max_length=1),
        ),
    ]
