# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0015_folder_typechar'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='bookings',
            field=models.ManyToManyField(through='personel.Registry', to='personel.Grader'),
        ),
    ]
