# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0016_folder_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='location',
            new_name='station',
        ),
        migrations.AddField(
            model_name='registry',
            name='action',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
