# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0017_auto_20160816_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='grader',
            name='currentFolder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
