# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0018_grader_currentfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField()),
                ('actionTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('station', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='registry',
            name='FolderID',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='GraderID',
        ),
        migrations.AlterField(
            model_name='folder',
            name='bookings',
            field=models.ManyToManyField(through='personel.Booking', to='personel.Grader'),
        ),
        migrations.DeleteModel(
            name='Registry',
        ),
        migrations.AddField(
            model_name='booking',
            name='FolderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Folder'),
        ),
        migrations.AddField(
            model_name='booking',
            name='GraderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Grader'),
        ),
    ]
