# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0019_auto_20160818_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.PositiveSmallIntegerField(default=None, null=True)),
                ('booksAbscent', models.PositiveSmallIntegerField(default=None, null=True)),
                ('booksZero', models.PositiveSmallIntegerField(default=None, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('ststusTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('LessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.Lesson')),
                ('SchoolToGradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
    ]
