# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0020_auto_20160818_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptance',
            old_name='ststusTime',
            new_name='statusTime',
        ),
        migrations.AddField(
            model_name='schooltograde',
            name='type',
            field=models.IntegerField(choices=[(1, b'\xce\x97\xce\x9c\xce\x95\xce\xa1\xce\x97\xce\xa3\xce\x99\xce\x9f'), (2, b'\xce\x95\xce\xa3\xce\xa0\xce\x95\xce\xa1\xce\x99\xce\x9d\xce\x9f')], default=1),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
    ]
