# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0021_auto_20160818_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='books',
            new_name='booksAB',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='folders',
            new_name='booksABFolders',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='foldersC',
            new_name='booksCFolders',
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
    ]
