# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0022_auto_20160819_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
        migrations.AlterUniqueTogether(
            name='acceptance',
            unique_together=set([('LessonID', 'SchoolToGradeID')]),
        ),
    ]
