# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0024_auto_20160821_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooltograde',
            old_name='codeDDE',
            new_name='ddeCode',
        ),
        migrations.RenameField(
            model_name='schooltograde',
            old_name='nameDDE',
            new_name='ddeName',
        ),
        migrations.AddField(
            model_name='specialty',
            name='code',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='statusTime',
            field=models.DateTimeField(blank=True, default=b'2016-08-28 21:38:23'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actionTime',
            field=models.DateTimeField(default=b'2016-08-28 21:38:23'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('LessonID', 'no', 'type')]),
        ),
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together=set([('code',)]),
        ),
    ]
