# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0042_auto_20160916_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='status',
            new_name='codeStatus',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='type',
            new_name='codeType',
        ),
        migrations.AddField(
            model_name='folder',
            name='codeLocation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='statusTime',
            field=models.DateTimeField(blank=True, default=b'2016-09-19 16:07:47'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actionTime',
            field=models.DateTimeField(default=b'2016-09-19 16:07:47'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='school',
            name='stype',
            field=models.IntegerField(choices=[(0, b'\xce\x93\xce\xa5\xce\x9c\xce\x9d\xce\x91\xce\xa3\xce\x99\xce\x9f'), (1, b'\xce\x9b\xce\xa5\xce\x9a\xce\x95\xce\x99\xce\x9f'), (3, b'\xce\x99\xce\x94\xce\x99\xce\xa9\xce\xa4\xce\x99\xce\x9a\xce\x9f'), (4, b'\xce\x91\xce\x9b\xce\x9b\xce\x9f')]),
        ),
        migrations.AlterField(
            model_name='schooltograde',
            name='type',
            field=models.IntegerField(choices=[(0, b'KENO'), (1, b'\xce\x97\xce\x9c\xce\x95\xce\xa1\xce\x97\xce\xa3\xce\x99\xce\x9f'), (2, b'\xce\x95\xce\xa3\xce\xa0\xce\x95\xce\xa1\xce\x99\xce\x9d\xce\x9f')], default=1),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='typeChar',
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('LessonID', 'no', 'codeType')]),
        ),
    ]
