# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0086_auto_20180429_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCenterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderBooks', models.SmallIntegerField(default=25)),
                ('minFolderBooks', models.SmallIntegerField(default=4)),
                ('maxActionDuration', models.SmallIntegerField(default=3)),
                ('name', models.CharField(default='43\u03bf \u0392\u039a \u0391\u0393\u03a1\u0399\u039d\u0399\u039fY', max_length=24)),
                ('article', models.CharField(default='o', max_length=2)),
                ('presidentName', models.CharField(default='\u0392\u0391\u03a3\u0399\u039b\u0395\u0399\u039f\u03a3', max_length=24)),
                ('presidentSurname', models.CharField(default='\u03a4\u0396\u039f\u03a5\u039c\u0391\u039a\u0391\u03a3', max_length=16)),
                ('phone', models.CharField(default=b'', max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='address',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='school',
            name='tk',
            field=models.CharField(default=b'', max_length=6),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='statusTime',
            field=models.DateTimeField(blank=True, default=b'2018-05-06 08:07:27'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actionTime',
            field=models.DateTimeField(default=b'2018-05-06 08:07:27'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
    ]
