# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 21:26
from __future__ import unicode_literals
from django.db import migrations

# vtzoum here
from django.contrib.auth.models import User, Group
from personel.models import GradeCenterInfo

def initial_data(apps, schema_editor):
    # We can't import the XXX model directly as it may be a newer
    # version than this migration expects. We use the historical version.
 

    #Person = apps.get_model("yourappname", "Person")    
    #Group = apps.get_model("bk043", "Group")    
    #User = apps.get_model("bk043", "User")    
    
    
    ######################################
    #GROUPS
    #g = Group.objects.get(name='groupname') 
    #g.user_set.add(your_user)
    groupnames=['Admin','Grammateia','Apothiki','Filaxi']
    for n in groupnames:
        obj, created = Group.objects.get_or_create(name=n)
        #g = Group.objects.create(name=n)

    # SUPERUSER
    User.objects.create_superuser('admin', 'myuser@mydomain.com', 'admin')

    #OTHER USERS
    #user = User.objects.create(username="username", password = "password", email="email")
    #u1 = User.objects.create(name="tzoumak")
    #user = User.objects.get(username="username")
    #user.set_password("password")
    #user.save()

    #USERS+BATCH
    usernames=['uA1','uA2','uF1','uF2',]
    for name in usernames:
        u1 = User.objects.create(username=name, password="1234")
    """
    usernames=['u1','u2','u3','u4','u5']
    for name in usernames:
        User.objects.get(username=name).set_password('1234'+name)
    """

    #USERS+BATCH+LIST
    userList=[ 
            #{'name':'tzoumak', 'passw':'1234', 'group':'Admin', 'staff': True},
            {'name':'Gramm1', 'passw':'1234', 'group':'Grammateia', 'staff': True},
            {'name':'uA1', 'passw':'1234', 'group':'Apothiki', 'staff': False},
            {'name':'uA2', 'passw':'1234', 'group':'Apothiki', 'staff': False},
            {'name':'uF1', 'passw':'1234', 'group':'Filaxi', 'staff': False},
            {'name':'uF2', 'passw':'1234', 'group':'Filaxi', 'staff': False},
            ]
    for u in userList:
        objUser, createdUser = User.objects.get_or_create(username=u['name'])
        print createdUser, objUser
        #update
        objUser.set_password(u['passw'])
        objUser.is_staff=u['staff']
        objUser.save()
        #set group
        objGroup, createdGroup = Group.objects.get_or_create(name=u['group'])
        objUser.groups.add(objGroup)
        #group = Group.objects.get(name=u['group']) 

        gc1 = GradeCenterInfo.objects.create(folderBooks=25, minFolderBooks=4, maxActionDuration=3,\
                name='43ο Β.Κ. ΑΙΤ-ΝΙΑΣ', article='ο', presidentName='Όνομα', presidentSurname='Επίθετο',\
                phone='26410 00000')


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0087_auto_20180506_0807'),
    ]

    
    operations = [ migrations.RunPython(initial_data),  ]



