# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0097_auto_20180512_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltograde',
            name='address',
            field=models.CharField(default=b'', max_length=48),
        ),
        migrations.AddField(
            model_name='schooltograde',
            name='city',
            field=models.CharField(default=b'', max_length=32),
        ),
        migrations.AddField(
            model_name='schooltograde',
            name='tk',
            field=models.CharField(default=b'', max_length=6),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='SchoolToGradeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personel.SchoolToGrade'),
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='statusTime',
            field=models.DateTimeField(blank=True, default=b'2018-05-12 00:21:39'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='actionTime',
            field=models.DateTimeField(default=b'2018-05-12 00:21:39'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='acceptances',
            field=models.ManyToManyField(through='personel.Acceptance', to='personel.SchoolToGrade'),
        ),
    ]
